import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Classes.module.css'
import { FaBars, FaPlusCircle } from 'react-icons/fa'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<nav className={styles.navigation}>
				<div className={styles.navContainer}>
					<FaBars className={styles.hamburgerMenu} />
					<div className={styles.mainLogo}>
						<Image
							src='/logos/prospectrove-logo.svg'
							width='200'
							height='60'
						/>
					</div>
				</div>
			</nav>
			<div className={styles.interface}>
				<nav className={styles.sidebar}>
					<ul>
						<li className={styles.sidebarButton}>
							<FaPlusCircle
								className={styles.sidebarButtonIcon}
							/>{' '}
							Account
						</li>
					</ul>
				</nav>
				<section className={styles.workArea}>
					<div className={styles.pageIndicator}>Account</div>
				</section>
			</div>
		</div>
	)
}
